services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
    labels:
      - 'traefik.http.middlewares.mybasicauth.basicauth.users=orpheus:$2y$05$3S79wq1BzC0.WN0i0Miv2eQ5eeyvn1KKWmbZHTFdjfEO48AmdGnx2'