services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
